#!/usr/bin/env ruby

require 'rubygems'
require 'bundler'
begin
  Bundler.setup(:default)
rescue Bundler::BundlerError => e
  $stderr.puts e.message
  $stderr.puts "Run `bundle install` to install missing gems"
  exit e.status_code
end

$: << File.expand_path("../../lib", __FILE__)

require 'sonar_connector'
require 'irb'

CONTROLLER = Sonar::Connector::Controller.new
CONTROLLER.prepare_connector
IRB.start
